CREATE DATABASE JSP_MVC2_EX;
	
USE JSP_MVC2_EX;

CREATE TABLE BOARD (
	NUM 		INT AUTO_INCREMENT PRIMARY KEY,
    WRITER 		VARCHAR(50),
    EMAIL 		VARCHAR(50),
    SUBJECT 	VARCHAR(50),
    PASSWORD 	VARCHAR(20),
    ENROLL_DT 	DATETIME,
    READ_CNT 	INT,
   	CONTENT 	VARCHAR(1000)
);
